export enum UserRoles {
  ADMIN = "ADMIN",
  STAFF = "STAFF",
  GUEST = "GUEST",
  CHEF = "CHEF",
}

export const RolePermissions: Record<UserRoles, string[]> = {
  [UserRoles.ADMIN]: [
    "getAllJobs",
    "getAllCandidates",
    "getAllCompanies",
    "getDetailCompany",
    "countJobsByMonth",
    "getTotalCards",
    "getTop5PostedJobs",
    "getRevenueReport",
    "deleteJob",
    "deleteCandidate",
    "deleteCompany",
    "searchJobs",
    "searchCandidates",
    "searchCompanies",
    "deleteCandidate",
    "syncJsonToMongoDB",
  ],
  [UserRoles.STAFF]: [
    "getAppliedJobs",
    "getSavedJobs",
    "createJobPost",
    "deleteJobPost",
    "getJobPostsByRecruiter",
    "setApplyStatus",
    "deleteApplication",
    "createNotification",
    "deposit",
    "payForJobPost",
    "getPaymentInfo",
    "resetPassword",
    "updateComapanyInfo",
    "updateComapanyAccount",
    "updateCandidatesStatus",
    "getApplicants",
  ],
  [UserRoles.GUEST]: [
    "getAppliedJobs",
    "getSavedJobs",
    "getCandidate",
    "updateCandidate",
    "getCandidateProfile",
    "updateCandidateProfile",
    "getGithubScore",
    "isLoggedInGithub",
    "getJobsByCandidate",
    "getJobDetailByCandidate",
    "saveJobPost",
    "unSaveJobPost",
    "createApplication",
    "getAllNotifications",
    "getUnreadCount",
    "markAllAsRead",
  ],
  [UserRoles.CHEF]: [
    "getAppliedJobs",
    "getSavedJobs",
    "getCandidate",
    "updateCandidate",
    "getCandidateProfile",
    "updateCandidateProfile",
    "getGithubScore",
    "isLoggedInGithub",
    "getJobsByCandidate",
    "getJobDetailByCandidate",
    "saveJobPost",
    "unSaveJobPost",
    "createApplication",
    "getAllNotifications",
    "getUnreadCount",
    "markAllAsRead",
  ],
};
